const API_BASE = 'https://fairway-forward-1.onrender.com';
const token = localStorage.getItem('ff_token');
const member = JSON.parse(localStorage.getItem('ff_member') || 'null');
const message = document.querySelector('#admin-message');
if (!token || member?.role !== 'admin') window.location.href = './index.html';
async function api(path, options = {}) { const response = await fetch(`${API_BASE}${path}`, { ...options, headers: { Authorization: `Bearer ${token}`, ...(options.headers || {}) } }); const data = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(data?.message || 'Request failed.'); return data; }
function showError(error) { message.textContent = error.message; }
function renderDraws(draws) { const list = document.querySelector('#draw-list'); list.innerHTML = draws.map(draw => `<div class="admin-row"><strong>${draw.month}</strong><span>£${draw.poolAmount.toLocaleString()} · ${draw.status}</span>${draw.status === 'scheduled' ? `<div class="admin-actions"><button data-publish="${draw._id}">Publish random draw</button><button data-publish="${draw._id}" data-numbers="true">Publish 10, 20, 30, 40, 45</button></div>` : `<span>Winning numbers: ${(draw.winningNumbers || []).join(', ')}</span>`}</div>`).join('') || '<p>No draws found.</p>'; }
function renderWinners(winners) { const list = document.querySelector('#winner-list'); list.innerHTML = winners.map(winner => `<div class="admin-row"><strong>${winner.user?.name || 'Member'} · ${winner.tier}/5</strong><span>£${winner.prizeAmount.toFixed(2)} · verification: ${winner.verificationStatus} · payout: ${winner.payoutStatus}</span><div class="admin-actions"><select data-status="${winner._id}"><option value="">Update status</option><option value="verificationStatus:approved">Approve proof</option><option value="verificationStatus:rejected">Reject proof</option><option value="payoutStatus:paid">Mark paid</option></select>${winner.proofUrl ? `<a href="${winner.proofUrl}" target="_blank">View proof</a>` : ''}</div></div>`).join('') || '<p>No winners yet.</p>'; }
async function load() { const [draws, winners] = await Promise.all([api('/api/draws'), api('/api/admin/winners')]); renderDraws(draws); renderWinners(winners); }
document.querySelector('#draw-list').addEventListener('click', async event => { const button = event.target.closest('[data-publish]'); if (!button) return; try { const winningNumbers = button.dataset.numbers ? [10,20,30,40,45] : undefined; await api(`/api/admin/draws/${button.dataset.publish}/publish`, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({winningNumbers}) }); message.textContent = 'Draw published and winners calculated.'; await load(); } catch (error) { showError(error); } });
document.querySelector('#winner-list').addEventListener('change', async event => { const value = event.target.value; if (!value) return; const [field, status] = value.split(':'); try { await api(`/api/admin/winners/${event.target.dataset.status}`, { method: 'PATCH', headers: {'Content-Type':'application/json'}, body: JSON.stringify({[field]: status}) }); message.textContent = 'Winner status updated.'; await load(); } catch (error) { showError(error); } });
document.querySelector('#logout').addEventListener('click', () => { localStorage.removeItem('ff_token'); localStorage.removeItem('ff_member'); localStorage.removeItem('ff_admin'); window.location.href = './index.html'; });
load().catch(showError);
